# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='SubGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateField(default=None)),
                ('Goal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracker.Goal')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(default='Test', max_length=128)),
                ('Cname', models.CharField(default='Test', max_length=128)),
                ('City', models.CharField(default='Test', max_length=128)),
                ('State', models.CharField(default='Test', max_length=128)),
                ('UID', models.CharField(default='Test', max_length=128)),
                ('Email', models.EmailField(default='', max_length=254)),
                ('PicUrl', models.URLField(default='http://ksmart.herokuapp.com')),
                ('PhoneNumber', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='User',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracker.User'),
        ),
    ]
