# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SubGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='PhoneNumber',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='PicUrl',
            field=models.URLField(default='http://ksmart.herokuapp.com'),
        ),
        migrations.AddField(
            model_name='user',
            name='UID',
            field=models.CharField(default='Test', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='Cname',
            field=models.CharField(default='Test', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='Pname',
            field=models.CharField(default='Test', max_length=128),
        ),
    ]
