# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='State',
            field=models.CharField(default='Test', max_length=128),
        ),
    ]
