# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20170721_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='City',
            field=models.CharField(default='Test', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='Cname',
            field=models.CharField(default='Test', max_length=128),
        ),
    ]
